"""把 AnimeStudio 以 JSON 导出的 Unity Mesh 写成 FBX 7.4 ASCII，带全部 UV 层与顶点色。

MCP 的 StaticMeshTools.import_file 只接受 fbx/obj，而 AnimeStudio 的 OBJ 只有 UV0、没有顶点色；
特效 shader 会读顶点色和第二/三套 UV，所以自己写 FBX。

坐标约定与 AnimeStudio 的 OBJ/FBX 导出一致：
    Unity 左手 Y 上 → FBX 右手 Y 上：位置/法线 X 取反，三角形顶点顺序反向；
    UV 原样写入（FBX 与 Unity 都是左下原点，UE 导入时自己翻 V，材质再翻回）；
    顶点写成厘米（×100），UnitScaleFactor=1：UE 的 FBX 导入不做单位换算，按文件数值当厘米。
顶点属性按"每顶点"映射（ByControlPoint / Direct），与 Unity 网格一一对应，不做焊接。

用法：python zzz_mesh_fbx.py <mesh.json> <out.fbx>
"""
import json
import sys
from pathlib import Path


def comps_of(arr, n):
    if not arr:
        return 0
    c = len(arr) // n
    if c * n != len(arr):
        raise ValueError("顶点数组长度 %d 不是顶点数 %d 的整数倍" % (len(arr), n))
    return c


def fmt(vals):
    return ",".join("%.7g" % v for v in vals)


def build(mesh):
    n = mesh["m_VertexCount"]
    name = mesh["m_Name"]
    v = mesh["m_Vertices"]
    c = comps_of(v, n)
    verts = []
    for i in range(n):
        verts += [-v[i * c] * 100.0, v[i * c + 1] * 100.0, v[i * c + 2] * 100.0]

    idx = mesh["m_Indices"]
    polys, mats = [], []
    start = 0
    for si, sm in enumerate(mesh["m_SubMeshes"]):
        if sm.get("topology", "Triangles") != "Triangles":
            raise ValueError("%s 子网格 %d 拓扑 %s 不支持" % (name, si, sm.get("topology")))
        cnt = sm["indexCount"]
        for f in range(start, start + cnt, 3):
            a, b, cc = idx[f + 2], idx[f + 1], idx[f]
            polys += [a, b, -cc - 1]
            mats.append(si)
        start += cnt
    if start != len(idx):
        raise ValueError("子网格索引数之和 %d 与索引总数 %d 不符" % (start, len(idx)))

    layers = []
    body = []
    nr = mesh.get("m_Normals")
    if nr:
        cn = comps_of(nr, n)
        out = []
        for i in range(n):
            out += [-nr[i * cn], nr[i * cn + 1], nr[i * cn + 2]]
        body.append('\t\tLayerElementNormal: 0 {\n\t\t\tVersion: 101\n\t\t\tName: ""\n'
                    '\t\t\tMappingInformationType: "ByControlPoint"\n\t\t\tReferenceInformationType: "Direct"\n'
                    '\t\t\tNormals: *%d {\n\t\t\t\ta: %s\n\t\t\t}\n\t\t}\n' % (len(out), fmt(out)))
        layers.append(("LayerElementNormal", 0))
    col = mesh.get("m_Colors")
    if col:
        if comps_of(col, n) != 4:
            raise ValueError("%s 顶点色不是 RGBA" % name)
        body.append('\t\tLayerElementColor: 0 {\n\t\t\tVersion: 101\n\t\t\tName: "Col"\n'
                    '\t\t\tMappingInformationType: "ByControlPoint"\n\t\t\tReferenceInformationType: "Direct"\n'
                    '\t\t\tColors: *%d {\n\t\t\t\ta: %s\n\t\t\t}\n\t\t}\n' % (len(col), fmt(col)))
        layers.append(("LayerElementColor", 0))
    uv_layers = 0
    for k in range(8):
        uv = mesh.get("m_UV%d" % k)
        if not uv:
            continue
        if k != uv_layers:
            raise ValueError("%s 的 UV%d 前面有缺失的 UV 层，FBX 层号会错位" % (name, k))
        cu = comps_of(uv, n)
        out = []
        for i in range(n):
            out += [uv[i * cu], uv[i * cu + 1]]
        body.append('\t\tLayerElementUV: %d {\n\t\t\tVersion: 101\n\t\t\tName: "UVChannel_%d"\n'
                    '\t\t\tMappingInformationType: "ByControlPoint"\n\t\t\tReferenceInformationType: "Direct"\n'
                    '\t\t\tUV: *%d {\n\t\t\t\ta: %s\n\t\t\t}\n\t\t}\n' % (k, k + 1, len(out), fmt(out)))
        uv_layers += 1
    body.append('\t\tLayerElementMaterial: 0 {\n\t\t\tVersion: 101\n\t\t\tName: ""\n'
                '\t\t\tMappingInformationType: "ByPolygon"\n\t\t\tReferenceInformationType: "IndexToDirect"\n'
                '\t\t\tMaterials: *%d {\n\t\t\t\ta: %s\n\t\t\t}\n\t\t}\n' % (len(mats), ",".join(map(str, mats))))
    layer_txt = '\t\tLayer: 0 {\n\t\t\tVersion: 100\n'
    for typ, i in layers + [("LayerElementMaterial", 0)] + ([("LayerElementUV", 0)] if uv_layers else []):
        layer_txt += '\t\t\tLayerElement:  {\n\t\t\t\tType: "%s"\n\t\t\t\tTypedIndex: %d\n\t\t\t}\n' % (typ, i)
    layer_txt += '\t\t}\n'
    for k in range(1, uv_layers):
        layer_txt += ('\t\tLayer: %d {\n\t\t\tVersion: 100\n\t\t\tLayerElement:  {\n\t\t\t\tType: "LayerElementUV"\n'
                      '\t\t\t\tTypedIndex: %d\n\t\t\t}\n\t\t}\n') % (k, k)

    geo_id, model_id = 1000001, 1000002
    mat_ids = [1000100 + i for i in range(len(mesh["m_SubMeshes"]))]
    out = []
    out.append('; FBX 7.4.0 project file\n; generated by GGYGO zzz_mesh_fbx.py\n\n')
    out.append('FBXHeaderExtension:  {\n\tFBXHeaderVersion: 1003\n\tFBXVersion: 7400\n\tCreator: "GGYGO zzz_mesh_fbx"\n}\n')
    out.append('GlobalSettings:  {\n\tVersion: 1000\n\tProperties70:  {\n'
               '\t\tP: "UpAxis", "int", "Integer", "",1\n\t\tP: "UpAxisSign", "int", "Integer", "",1\n'
               '\t\tP: "FrontAxis", "int", "Integer", "",2\n\t\tP: "FrontAxisSign", "int", "Integer", "",1\n'
               '\t\tP: "CoordAxis", "int", "Integer", "",0\n\t\tP: "CoordAxisSign", "int", "Integer", "",1\n'
               '\t\tP: "UnitScaleFactor", "double", "Number", "",1\n\t}\n}\n')
    out.append('Definitions:  {\n\tVersion: 100\n\tCount: %d\n'
               '\tObjectType: "Model" {\n\t\tCount: 1\n\t}\n\tObjectType: "Geometry" {\n\t\tCount: 1\n\t}\n'
               '\tObjectType: "Material" {\n\t\tCount: %d\n\t}\n}\n' % (2 + len(mat_ids), len(mat_ids)))
    out.append('Objects:  {\n')
    out.append('\tGeometry: %d, "Geometry::%s", "Mesh" {\n' % (geo_id, name))
    out.append('\t\tVertices: *%d {\n\t\t\ta: %s\n\t\t}\n' % (len(verts), fmt(verts)))
    out.append('\t\tPolygonVertexIndex: *%d {\n\t\t\ta: %s\n\t\t}\n' % (len(polys), ",".join(map(str, polys))))
    out.append('\t\tGeometryVersion: 124\n')
    out += body
    out.append(layer_txt)
    out.append('\t}\n')
    out.append('\tModel: %d, "Model::%s", "Mesh" {\n\t\tVersion: 232\n\t\tProperties70:  {\n'
               '\t\t\tP: "Lcl Scaling", "Lcl Scaling", "", "A",1,1,1\n\t\t}\n\t\tShading: T\n\t\tCulling: "CullingOff"\n\t}\n'
               % (model_id, name))
    for i, mid in enumerate(mat_ids):
        out.append('\tMaterial: %d, "Material::%s_%d", "" {\n\t\tVersion: 102\n\t\tShadingModel: "phong"\n\t}\n'
                   % (mid, name, i))
    out.append('}\n')
    out.append('Connections:  {\n\tC: "OO",%d,0\n\tC: "OO",%d,%d\n' % (model_id, geo_id, model_id))
    for mid in mat_ids:
        out.append('\tC: "OO",%d,%d\n' % (mid, model_id))
    out.append('}\n')
    return "".join(out)


def main():
    mesh = json.load(open(sys.argv[1], encoding="utf-8"))
    out = Path(sys.argv[2])
    out.write_text(build(mesh), encoding="utf-8")
    print(out)


if __name__ == "__main__":
    main()
